# Что за Workflow
name: "Builg & Test"

# Когда он запускается
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build_n_test:
    name: Настройка, сборка и тестирование
    # Контейнер, в котором запускается задание

    # Разные сочетания для проверки
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - 3.12
        gcc_version:
          - 13.2
        exercise:
          - 00.CI_example

    runs-on:  "${{ matrix.os }}"

    # Шаги задания
    steps:
      - name: Печать окружения. Окружение — это интересно.
        run: env

      - name: Установка make и некоторых других инструментов
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      # Егор Тенсин учился на Матмехе СПбГУ
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: "${{ matrix.gcc_version }}"
          platform: x64

      - name: Установка Питона (или Пайтона?..)
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Берём исходники из Гита
        uses: actions/checkout@v4

      - name: Собираем программу
        run: |
          cd ${{ matrix.exercise }}
          ./build.sh
          ./test.sh
          cd ..

      - name: Тестируем программу
        run: |
          cd ${{ matrix.exercise }}
          ./test.sh
          cd ..
